### ISSUE TITLE
A new large-scale unsupervised segmentation benchmark ImageNet-S

### ISSUE THREAD

**Issue by gasvn** [Mirsadeghi/Awesome-Unsupervised-Segmentation#2]
[Large-scale Unsupervised Semantic Segmentation](https://arxiv.org/abs/2106.03149)
ImageNet-S dataset: https://github.com/UnsupervisedSemanticSegmentation/ImageNet-S

**Comment by Mirsadeghi** [comment]
Thank you @gasvn  for your contribution. I will create a new section for datasets.
